-- ============================================================
-- Vehicle Insurance Portal — Malath Insurance
-- File: triggers.sql
-- Description: Automation triggers for the Vehicle Insurance
--              Portal database.
--
--              1) Business logic trigger — automatically
--                 activates a Policy once its Payment is
--                 recorded.
--              2) Audit-trail triggers — applied identically
--                 across all six core tables (Owner, Policy,
--                 Vehicle, Coverage, Payments, Claims) to track
--                 who created/modified each record and when:
--                   - CreationBY        (set on INSERT)
--                   - CreationDate      (set on INSERT)
--                   - ModifiedBY        (set on UPDATE)
--                   - LastModifiedDate  (set on UPDATE)
--
-- Total: 25 triggers (6 tables x 4 audit triggers + 1 policy
--        activation trigger), matching the deployed schema.
-- ============================================================


-- ------------------------------------------------------------
-- 1. Business Logic Trigger: Auto-activate policy on payment
-- ------------------------------------------------------------

DROP TRIGGER ITURKI.TRG_UPDATE_PLICY_STATUS;

CREATE OR REPLACE TRIGGER ITURKI.TRG_UPDATE_Plicy_Status
AFTER INSERT ON ITURKI.PAYMENTS
FOR EACH ROW
BEGIN
    UPDATE policy
    SET Policy_Status = 'Active'
    WHERE Policy_ID = :NEW.Policy_ID;
END;
/


-- ------------------------------------------------------------
-- 2. Audit Trail Triggers
-- ------------------------------------------------------------

-- === CLAIMS ===

DROP TRIGGER ITURKI.UPDATECLAIMS_TIMESTAMP;
CREATE OR REPLACE TRIGGER ITURKI.UPDATECLAIMS_TIMESTAMP
BEFORE UPDATE ON ITURKI.Claims
FOR EACH ROW
BEGIN
    :NEW.LastModifiedDate := CURRENT_TIMESTAMP;
END;
/

DROP TRIGGER ITURKI.UPDATECLAIMS2_TIMESTAMP;
CREATE OR REPLACE TRIGGER ITURKI.UPDATECLAIMS2_TIMESTAMP
BEFORE INSERT ON ITURKI.Claims
FOR EACH ROW
BEGIN
    :NEW.CreationBY := User;
END;
/

DROP TRIGGER ITURKI.UPDATECLAIMS3_TIMESTAMP;
CREATE OR REPLACE TRIGGER ITURKI.UPDATECLAIMS3_TIMESTAMP
BEFORE INSERT ON ITURKI.Claims
FOR EACH ROW
BEGIN
    :NEW.CreationDate := CURRENT_TIMESTAMP;
END;
/

DROP TRIGGER ITURKI.UPDATECLAIMS4_TIMESTAMP;
CREATE OR REPLACE TRIGGER ITURKI.UPDATECLAIMS4_TIMESTAMP
BEFORE UPDATE ON ITURKI.Claims
FOR EACH ROW
BEGIN
    :NEW.ModifiedBY := User;
END;
/

-- === COVERAGE ===

DROP TRIGGER ITURKI.UPDATECOVERAGE_TIMESTAMP;
CREATE OR REPLACE TRIGGER ITURKI.UPDATECOVERAGE_TIMESTAMP
BEFORE UPDATE ON ITURKI.Coverage
FOR EACH ROW
BEGIN
    :NEW.LastModifiedDate := CURRENT_TIMESTAMP;
END;
/

DROP TRIGGER ITURKI.UPDATECOVERAGE2_TIMESTAMP;
CREATE OR REPLACE TRIGGER ITURKI.UPDATECOVERAGE2_TIMESTAMP
BEFORE INSERT ON ITURKI.Coverage
FOR EACH ROW
BEGIN
    :NEW.CreationBY := User;
END;
/

DROP TRIGGER ITURKI.UPDATECOVERAGE3_TIMESTAMP;
CREATE OR REPLACE TRIGGER ITURKI.UPDATECOVERAGE3_TIMESTAMP
BEFORE INSERT ON ITURKI.Coverage
FOR EACH ROW
BEGIN
    :NEW.CreationDate := CURRENT_TIMESTAMP;
END;
/

DROP TRIGGER ITURKI.UPDATECOVERAGE4_TIMESTAMP;
CREATE OR REPLACE TRIGGER ITURKI.UPDATECOVERAGE4_TIMESTAMP
BEFORE UPDATE ON ITURKI.Coverage
FOR EACH ROW
BEGIN
    :NEW.ModifiedBY := User;
END;
/

-- === OWNER ===

DROP TRIGGER ITURKI.UPDATEOWNER_TIMESTAMP;
CREATE OR REPLACE TRIGGER ITURKI.UPDATEOWNER_TIMESTAMP
BEFORE UPDATE ON ITURKI.Owner
FOR EACH ROW
BEGIN
    :NEW.LastModifiedDate := CURRENT_TIMESTAMP;
END;
/

DROP TRIGGER ITURKI.UPDATEOWNER2_TIMESTAMP;
CREATE OR REPLACE TRIGGER ITURKI.UPDATEOWNER2_TIMESTAMP
BEFORE INSERT ON ITURKI.Owner
FOR EACH ROW
BEGIN
    :NEW.CreationBY := User;
END;
/

DROP TRIGGER ITURKI.UPDATEOWNER3_TIMESTAMP;
CREATE OR REPLACE TRIGGER ITURKI.UPDATEOWNER3_TIMESTAMP
BEFORE INSERT ON ITURKI.Owner
FOR EACH ROW
BEGIN
    :NEW.CreationDate := CURRENT_TIMESTAMP;
END;
/

DROP TRIGGER ITURKI.UPDATEOWNER4_TIMESTAMP;
CREATE OR REPLACE TRIGGER ITURKI.UPDATEOWNER4_TIMESTAMP
BEFORE UPDATE ON ITURKI.Owner
FOR EACH ROW
BEGIN
    :NEW.ModifiedBY := User;
END;
/

-- === PAYMENTS ===

DROP TRIGGER ITURKI.UPDATEPAYMENTS_TIMESTAMP;
CREATE OR REPLACE TRIGGER ITURKI.UPDATEPAYMENTS_TIMESTAMP
BEFORE UPDATE ON ITURKI.Payments
FOR EACH ROW
BEGIN
    :NEW.LastModifiedDate := CURRENT_TIMESTAMP;
END;
/

DROP TRIGGER ITURKI.UPDATEPAYMENTS2_TIMESTAMP;
CREATE OR REPLACE TRIGGER ITURKI.UPDATEPAYMENTS2_TIMESTAMP
BEFORE INSERT ON ITURKI.Payments
FOR EACH ROW
BEGIN
    :NEW.CreationBY := User;
END;
/

DROP TRIGGER ITURKI.UPDATEPAYMENTS3_TIMESTAMP;
CREATE OR REPLACE TRIGGER ITURKI.UPDATEPAYMENTS3_TIMESTAMP
BEFORE INSERT ON ITURKI.Payments
FOR EACH ROW
BEGIN
    :NEW.CreationDate := CURRENT_TIMESTAMP;
END;
/

DROP TRIGGER ITURKI.UPDATEPAYMENTS4_TIMESTAMP;
CREATE OR REPLACE TRIGGER ITURKI.UPDATEPAYMENTS4_TIMESTAMP
BEFORE UPDATE ON ITURKI.Payments
FOR EACH ROW
BEGIN
    :NEW.ModifiedBY := User;
END;
/

-- === POLICY ===

DROP TRIGGER ITURKI.UPDATEPOLICY_TIMESTAMP;
CREATE OR REPLACE TRIGGER ITURKI.UPDATEPOLICY_TIMESTAMP
BEFORE UPDATE ON ITURKI.Policy
FOR EACH ROW
BEGIN
    :NEW.LastModifiedDate := CURRENT_TIMESTAMP;
END;
/

DROP TRIGGER ITURKI.UPDATEPOLICY2_TIMESTAMP;
CREATE OR REPLACE TRIGGER ITURKI.UPDATEPOLICY2_TIMESTAMP
BEFORE INSERT ON ITURKI.Policy
FOR EACH ROW
BEGIN
    :NEW.CreationBY := User;
END;
/

DROP TRIGGER ITURKI.UPDATEPOLICY3_TIMESTAMP;
CREATE OR REPLACE TRIGGER ITURKI.UPDATEPOLICY3_TIMESTAMP
BEFORE INSERT ON ITURKI.Policy
FOR EACH ROW
BEGIN
    :NEW.CreationDate := CURRENT_TIMESTAMP;
END;
/

DROP TRIGGER ITURKI.UPDATEPOLICY4_TIMESTAMP;
CREATE OR REPLACE TRIGGER ITURKI.UPDATEPOLICY4_TIMESTAMP
BEFORE UPDATE ON ITURKI.Policy
FOR EACH ROW
BEGIN
    :NEW.ModifiedBY := User;
END;
/

-- === VEHICLE ===

DROP TRIGGER ITURKI.UPDATEVEHICLE_TIMESTAMP;
CREATE OR REPLACE TRIGGER ITURKI.UPDATEVEHICLE_TIMESTAMP
BEFORE UPDATE ON ITURKI.Vehicle
FOR EACH ROW
BEGIN
    :NEW.LastModifiedDate := CURRENT_TIMESTAMP;
END;
/

DROP TRIGGER ITURKI.UPDATEVEHICLE2_TIMESTAMP;
CREATE OR REPLACE TRIGGER ITURKI.UPDATEVEHICLE2_TIMESTAMP
BEFORE INSERT ON ITURKI.Vehicle
FOR EACH ROW
BEGIN
    :NEW.CreationBY := User;
END;
/

DROP TRIGGER ITURKI.UPDATEVEHICLE3_TIMESTAMP;
CREATE OR REPLACE TRIGGER ITURKI.UPDATEVEHICLE3_TIMESTAMP
BEFORE INSERT ON ITURKI.Vehicle
FOR EACH ROW
BEGIN
    :NEW.CreationDate := CURRENT_TIMESTAMP;
END;
/

DROP TRIGGER ITURKI.UPDATEVEHICLE4_TIMESTAMP;
CREATE OR REPLACE TRIGGER ITURKI.UPDATEVEHICLE4_TIMESTAMP
BEFORE UPDATE ON ITURKI.Vehicle
FOR EACH ROW
BEGIN
    :NEW.ModifiedBY := User;
END;
/
